name: sticky_headers
description: Flutter Sticky Headers - Lets you place headers on scrollable content that will stick to the top of the container whilst the content is scrolled.
version: 0.2.0
homepage: https://github.com/fluttercommunity/flutter_sticky_headers
maintainer: Simon Lightfoot (@slightfoot)

environment:
  sdk: ">=2.17.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
